### ISSUE TITLE
Party List has stray pixels

### ISSUE THREAD

**Issue by ashleykinard** [ValeriaeWasTaken/Material-UI-Reborn#5] opened 2024-08-13 04:03 UTC
Noticed that there are stray pixels in the party list with the **Party and Alliance Background** setting set to **Black** (names blurred intentionally).
![123](https://github.com/user-attachments/assets/d88a08ff-30d6-4c21-9b09-b6b210b02db0)
It's hard to see, but pretty visible on the party member 6.

I checked also setting **Party and Alliance Background** to **Transparent** and the pixels are still present:
![456](https://github.com/user-attachments/assets/49f6da14-40c3-42dd-8f58-f9c6b945afda)

**Comment by ValeriaeWasTaken** [comment] 2024-08-17 19:08
Closing cause I am unable to reproduce with any settings. Probably had something to do with other UI mods installed at the time as MUI:R didn't have chocobo icons when this issue was created.

**Closed as completed by ValeriaeWasTaken** 2024-08-17 19:08 UTC
